### ISSUE TITLE
The "output" argument is not copied from vm

### ISSUE THREAD

**Issue by zeule** [alandefreitas/clang-unformat#9]
... in parse_cli() and ignored?

**Comment by alandefreitas** [comment]
What?

**Comment by zeule** [comment]
https://github.com/alandefreitas/clang-unformat/blob/master/standalone/cli_config.cpp#L63 you do not set `c.output`.

**Comment by alandefreitas** [comment]
Oh... what a terrible option name :laughing: 

https://github.com/alandefreitas/clang-unformat/blob/a53f0a64d3e34c5f42fc0942f16623a15367eba1/standalone/cli_config.cpp#L48

You're correct. I think everyone has always used the default output location

https://github.com/alandefreitas/clang-unformat/blob/a53f0a64d3e34c5f42fc0942f16623a15367eba1/standalone/cli_config.cpp#L137

so we just never noticed the problem.

This fix is trivial: 

https://github.com/alandefreitas/clang-unformat/blob/a53f0a64d3e34c5f42fc0942f16623a15367eba1/standalone/cli_config.cpp#L63

should be followed by `c.output = vm["output"].as<fs::path>();`.

We can also check if explicitly checking the output can cause any problems in 

https://github.com/alandefreitas/clang-unformat/blob/a53f0a64d3e34c5f42fc0942f16623a15367eba1/standalone/cli_config.cpp#L133

but I just went through that and I don't think so.

**Comment by zeule** [comment]
I made the same trivial change earlier today, and it works for me as well.

**Comment by alandefreitas** [comment]
Since you caught the problem, do you want to open the PR?

**Comment by zeule** [comment]
Not really, thank you.

**Comment by zeule** [comment]
Thanks!
